/// Flutter icons MyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
library;
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const String _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData camera = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData invisiblityicon = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData reels = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData post = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData call = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData comment = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData visiblityicon = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData messenger = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData save = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData tag = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData camera_1 = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData verify = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData price = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData videocam = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData homeFilled = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData grid = IconData(0xe98b, fontFamily: _kFontFam);
}
